---
title: "Bienvenides a la Ciencia de Datos <br> `r emo::ji('rocket')`"
author: ""
date: "2 de marzo de 2020"
output:
  xaringan::moon_reader:
    seal: False
    css: ["../mainStyle.css", "../vendor/fontawesome/css/all.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: solarized-light
      countIncrementalSlides: false
---

```{r child = "../setup.Rmd"}
```

class: inverse, center, middle, title-slide, animated, slideInDown

# L01: Bienvenides a la Ciencia de Datos <br> `r emo::ji('rocket')`

### 2 de marzo de 2020

---

## hola_mundo()

--

- Pablo Reyes 🧔🏾

--

- Política y AP (2014-2018)

--

- Buendía & Laredo | Lex ++

--

- Programación (JS, Python y R) + estadística

--

- Encuestas
- Seguimiento de actores en medios y redes
- Repositorio legal

--

---
class: inverse, center, middle

### ¡Cuéntenme de ustedes!

¿Cuáles son sus temas de interés?

¿Han usado <i class="fab fa-r-project"></i>?

---

layout: true

## ¿Qué esperar de este curso?

<div class="footer">
<span>
Ciencia de Datos en R `r emo::ji('rocket')` Todo el material está disponible en <a href="https://github.com/pablorm296/CursoR">GitHub</a>
</span>
</div> 

---

--

Este es un curso introductorio a la ciencia de datos con un ligero énfasis en temas de ciencia política e inferencia estadística.

---

- Aprenderemos a procesar datos `r emo::ji('wrench')`
- Aprenderemos a comunicar (visualizar y generación de documentos) `r emo::ji('bar_chart')`
- Aprenderemos a programar `r emo::ji('computer')`
- Aprenderemos a generar conocimiento (inferir, modelar y predecir) `r emo::ji('mag')`


Todo esto, mientras usamos <i class="fab fa-r-project"></i> (y otras herramientas).

---

**¿Necesito saber estadística o programación?**

--

No. Todos partiremos "desde cero".

--

**¿Este es un curso de metodología cuanti / estadística?**

--

No, en el sentido de que no ahondaremos en detalles teóricos. Sin embargo, cuando lleguemos a la Unidad II, trabajaremos frecuentemente con temas de estadística (usar R para inferir, predecir y explicar). Piénsenlo como un repaso / introducción general.

---

**¿Donde puedo leer más sobre métodos cuantis / estadística?**

--

Alan Agresti y Barbara Finlay, _Statistical Methods for the Social Sciences_ y otros documentos citados en README.md (más sobre esto al rato).

--

**¿Por qué** <i class="fab fa-r-project"></i>**?**

--

- Proyecto de código libre y abierto (SPSS: +1000 USD/año, STATA: +900 USD/año)

--

- Hacer estadística en R es ridículamente fácil (a diferencia de <i class="fab fa-python"></i>)

--

- `ggplot2`: Una de las mejores herramientas para la visualización de datos

---

layout: true
  
<div class="footer">
<span>
Ciencia de Datos en R `r emo::ji('rocket')` Todo el material está disponible en <a href="https://github.com/pablorm296/CursoR">GitHub</a>
</span>
</div> 

---

## Dinámica de la clase

- Aprender haciendo
- Siéntanse libres de interrumpir y preguntar
- Cuando trabajemos con código: primero yo, después ustedes
- Tareas.
  - Usen el grupo de WA para dudas
  - `r emo::ji('no_good')` Tengo duda con la pregunta 2
  - `r emo::ji('+1')` Tengo una duda con el uso de `filter()`

---

## El internet es su mejor amigo

- A menos que indique lo contrario, el re-uso de código está permitido (obvio, indicando la fuente).
- Google: *r split string by character*
- Google: *ggplot2 save as svg*
- Google: *r error cannot change working directory*
- https://stackoverflow.com/

